export const LEVELS = [
  {
    "name": "튜토리얼 1) 기본 (3x3)",
    "nameKey": "level.tutorial_1.name",
    "desc": "아무 칸에서 시작해 모든 칸을 정확히 1번씩 방문하세요.",
    "descKey": "level.tutorial_1.desc",
    "grid": ["...", "...", "..."],
    "stitches": [],
  },
  {
    "name": "튜토리얼 2) Turn(any)",
    "nameKey": "level.tutorial_2.name",
    "desc": "이 아이콘(꺾임)은 해당 칸에서 반드시 방향을 꺾어야 합니다.",
    "descKey": "level.tutorial_2.desc",
    "grid": [".t..", "....", "..t.", "...."],
    "stitches": [],
  },
  {
    "name": "튜토리얼 3) Straight + H/V",
    "nameKey": "level.tutorial_3.name",
    "desc": "직진/가로/세로 힌트는 해당 칸에서 '직진' 형태를 강제합니다.",
    "descKey": "level.tutorial_3.desc",
    "grid": [".h..", ".s..", "..v.", "...."],
    "stitches": [],
  },
  {
    "name": "튜토리얼 4) CW / CCW",
    "nameKey": "level.tutorial_4.name",
    "desc": "CW(r)는 이전→다음 이동이 시계 방향 회전이어야 하고, CCW(l)는 반시계 방향 회전이어야 합니다.",
    "descKey": "level.tutorial_4.desc",
    "grid": ["....", ".r..", "..l.", "...."],
    "stitches": [],
  },
  {
    "name": "튜토리얼 5) Cross Stitch",
    "nameKey": "level.tutorial_5.name",
    "desc": "X 꼭짓점에서는 두 대각선 연결(↘︎↖︎, ↙︎↗︎)이 모두 강제됩니다. 따라서 대각선 이동이 필요합니다.",
    "descKey": "level.tutorial_5.desc",
    "grid": ["....", "....", "....", "...."],
    "stitches": [[2, 2]],
  },
  {
    "name": "튜토리얼 6) Corner Count (0-3)",
    "nameKey": "level.tutorial_6.name",
    "desc": "숫자는 해당 꼭짓점 주변 4칸 사이에서 경로가 만드는 연결 수(0~3)를 뜻합니다.",
    "descKey": "level.tutorial_6.desc",
    "grid": ["....", "....", "....", "...."],
    "stitches": [],
    "cornerCounts": [[1, 1, 2], [1, 3, 1]],
  },
  {
    "name": "튜토리얼 7) 가위/바위/보 순서",
    "nameKey": "level.tutorial_7.name",
    "desc": "이 심볼 타일만 따로 봤을 때 방문 순서가 가위→바위→보→가위…(승자 순환)여야 합니다.",
    "descKey": "level.tutorial_7.desc",
    "grid": ["g...", ".b..", "..p.", "...."],
    "stitches": [],
  },
  {
    "name": "튜토리얼 8) 움직이는 벽",
    "nameKey": "level.tutorial_8.name",
    "desc": "벽(이동 가능)을 드래그해서 빈 칸으로 옮기세요. (힌트/가위바위보 타일 위에는 놓을 수 없음)",
    "descKey": "level.tutorial_8.desc",
    "grid": [".....", ".....", ".mh..", ".....", "....."],
    "stitches": [],
  },
  {
    "name": "파일럿 1) Basic (4x4)",
    "nameKey": "level.pilot_1.name",
    "desc": "힌트 섞인 기본형.",
    "descKey": "level.pilot_1.desc",
    "grid": [".ts.", "s..t", "....", "...."],
    "stitches": [],
  },
  {
    "name": "파일럿 2) Axis Locks (5x5)",
    "nameKey": "level.pilot_2.name",
    "desc": "가로/세로 직진 힌트로 공간을 잠그는 유형.",
    "descKey": "level.pilot_2.desc",
    "grid": ["...t.", "....v", ".v...", ".v.tt", "...h."],
    "stitches": [],
  },
  {
    "name": "파일럿 3) CW/CCW + Walls (5x5)",
    "nameKey": "level.pilot_3.name",
    "desc": "방향성 꺾임 + 벽 조합.",
    "descKey": "level.pilot_3.desc",
    "grid": ["..##.", "..l#.", "...l.", ".lr..", "...r."],
    "stitches": [],
  },
  {
    "name": "파일럿 4) Cross Stitch (5x5)",
    "nameKey": "level.pilot_4.name",
    "desc": "스티치 1개.",
    "descKey": "level.pilot_4.desc",
    "grid": [".tt..", "..t..", "....t", ".v...", ".t..."],
    "stitches": [[2, 2]],
  },
  {
    "name": "파일럿 5) Multi Stitch + CW/CCW (6x6)",
    "nameKey": "level.pilot_5.name",
    "desc": "스티치 다중 + 방향성 꺾임.",
    "descKey": "level.pilot_5.desc",
    "grid": [".....r", "..l...", ".r....", "......", ".s.tv.", "..r..."],
    "stitches": [[2, 2], [2, 4], [4, 3]],
  },
  {
    "name": "파일럿 6) Stitch in a Broken Field (6x6)",
    "nameKey": "level.pilot_6.name",
    "desc": "벽이 많을 때 스티치가 만드는 강제 분기.",
    "descKey": "level.pilot_6.desc",
    "grid": ["......", "....t.", "#t.t..", "##..t.", "th.#..", ".##..."],
    "stitches": [[2, 4]],
  },
  {
    "name": "파일럿 7) Stress (7x7)",
    "nameKey": "level.pilot_7.name",
    "desc": "스티치 + 벽 + 방향 힌트 혼합.",
    "descKey": "level.pilot_7.desc",
    "grid": ["..#l...", ".......", ".#v....", "v...##.", "..#s#..", "rr#....", "..h..#."],
    "stitches": [[5, 1], [1, 5]],
  },
  {
    "name": "파일럿 8) RPS Spread (5x5)",
    "nameKey": "level.pilot_8.name",
    "desc": "가위/바위/보 타일을 순서대로 '통과'하도록 경로를 설계해 보세요.",
    "descKey": "level.pilot_8.desc",
    "grid": ["g...b", ".....", "b.p..", ".....", "p...g"],
    "stitches": [],
  },
  {
    "name": "파일럿 9) RPS + Stitch (5x5)",
    "nameKey": "level.pilot_9.name",
    "desc": "RPS 순서 제약 + 스티치(대각선 강제) 결합.",
    "descKey": "level.pilot_9.desc",
    "grid": ["g...b", ".....", "b.p..", ".....", "p...g"],
    "stitches": [[2, 2]],
  },
  {
    "name": "파일럿 10) Movable Walls x2 (6x6)",
    "nameKey": "level.pilot_10.name",
    "desc": "이동 가능한 벽 2개. 퍼즐을 풀기 전에 벽을 재배치해 보세요.",
    "descKey": "level.pilot_10.desc",
    "grid": ["......", "..m...", "..t#..", ".h....", "...m..", "......"],
    "stitches": [],
  },
  {
    "name": "파일럿 11) Corner Weave (6x6)",
    "nameKey": "level.pilot_11.name",
    "desc": "Corner count + 방향성 힌트 + 스티치 조합. 제약을 만족하는 순서가 다른 해법이 2개 이상 존재합니다.",
    "descKey": "level.pilot_11.desc",
    "grid": [".....r", "..l...", ".r....", "......", ".s.tv.", "..r..."],
    "stitches": [[2, 2], [2, 4], [4, 3]],
    "cornerCounts": [[1, 2, 3], [3, 2, 2], [5, 4, 2]],
  },
  {
    "name": "파일럿 12) Stress Corners (7x7)",
    "nameKey": "level.pilot_12.name",
    "desc": "Stress 패턴에 corner count를 추가한 고난도. 서로 다른 순서로 제약을 달성하는 복수 해법이 존재합니다.",
    "descKey": "level.pilot_12.desc",
    "grid": ["..#l...", ".......", ".#v....", "v...##.", "..#s#..", "rr#....", "..h..#."],
    "stitches": [[5, 1], [1, 5]],
    "cornerCounts": [[2, 2, 2], [4, 4, 1], [6, 4, 3]],
  },
];

export const DEFAULT_LEVEL_INDEX = 0;
