// @ts-nocheck
export const normalizeNotificationToggleOptions = (options = {}) => {
  const {
    elementIds,
    notificationEnabledKey,
    autoUpdateEnabledKey,
    notificationAutoPromptDecisions,
    readAutoPromptDecision = () => notificationAutoPromptDecisions?.UNSET,
    writeAutoPromptDecision = () => { },
    readNotificationEnabledPreference = () => false,
    writeNotificationEnabledPreference = () => { },
    readAutoUpdateEnabledPreference = () => false,
    writeAutoUpdateEnabledPreference = () => { },
    hasStoredNotificationEnabledPreference = () => false,
    notificationPermissionState = () => 'unsupported',
    supportsNotifications = () => false,
    canUseServiceWorker = () => false,
    requestNotificationPermission = async () => 'unsupported',
    syncDailyStateToServiceWorker = async () => { },
    syncUpdatePolicyToServiceWorker = async () => { },
    registerBackgroundDailyCheck = async () => { },
    requestServiceWorkerDailyCheck = async () => { },
    translateNow = (key) => key,
    showInAppToast = () => { },
    windowObj = typeof window === 'undefined' ? undefined : window,
    documentObj = typeof document === 'undefined' ? undefined : document,
  } = options;

  return {
    elementIds,
    notificationEnabledKey,
    autoUpdateEnabledKey,
    notificationAutoPromptDecisions,
    readAutoPromptDecision,
    writeAutoPromptDecision,
    readNotificationEnabledPreference,
    writeNotificationEnabledPreference,
    readAutoUpdateEnabledPreference,
    writeAutoUpdateEnabledPreference,
    hasStoredNotificationEnabledPreference,
    notificationPermissionState,
    supportsNotifications,
    canUseServiceWorker,
    requestNotificationPermission,
    syncDailyStateToServiceWorker,
    syncUpdatePolicyToServiceWorker,
    registerBackgroundDailyCheck,
    requestServiceWorkerDailyCheck,
    translateNow,
    showInAppToast,
    windowObj,
    documentObj,
  };
};
