import { createSwMessenger } from './sw_messenger.js';
import { createSwUpdateOrchestrator } from './sw_update_orchestrator.js';

export function createUpdateFlow(options = {}) {
  const {
    swMessageTypes,
    updateApplyStatus,
    updateCheckDecision,
    localBuildNumber = 0,
    versionUrl = '',
    swBuildNumberRe = null,
    resolveServiceWorkerRegistrationUrl,
    isLocalhostHostname,
    readAutoUpdateEnabledPreference = () => false,
    readNotificationEnabledPreference = () => false,
    readLastNotifiedRemoteBuildNumber = () => null,
    writeLastNotifiedRemoteBuildNumber = () => { },
    buildNotificationTextPayload = () => ({}),
    getLatestDailyState = () => ({
      dailyId: null,
      hardInvalidateAtUtcMs: null,
      dailySolvedDate: null,
    }),
    resolveUpdateCheckDecision = () => null,
    shouldResyncManualUpdatePolicy = () => false,
    showInAppToast = () => { },
    resolveNewVersionToastText = () => '',
    resolveNewVersionTitleText = () => '',
    resolveNewVersionBodyText = () => '',
    resolveUpdateApplyFailureToastText = () => '',
    setUpdateProgressOverlayActive = () => { },
    updateCheckThrottleMs = 5 * 60 * 1000,
    updateApplyReloadFallbackMs = 5 * 1000,
    dailyCheckTag = 'tether-daily-check',
    dailyNotificationWarningHours = 8,
    waitingWorkerTimeoutFirstMs = 8000,
    waitingWorkerTimeoutRetryMs = 4000,
    fetchImpl = typeof fetch === 'function' ? fetch : null,
    windowObj = typeof window !== 'undefined' ? window : undefined,
    documentObj = typeof document !== 'undefined' ? document : undefined,
    navigatorObj = typeof navigator !== 'undefined' ? navigator : undefined,
    notificationApi = typeof Notification !== 'undefined' ? Notification : undefined,
    now = () => Date.now(),
    messageChannelFactory,
  } = options;

  const swMessenger = createSwMessenger({
    windowObj,
    navigatorObj,
    messageChannelFactory,
  });

  const swUpdateOrchestrator = createSwUpdateOrchestrator({
    swMessenger,
    swMessageTypes,
    updateApplyStatus,
    updateCheckDecision,
    localBuildNumber,
    versionUrl,
    swBuildNumberRe,
    resolveServiceWorkerRegistrationUrl,
    isLocalhostHostname,
    readAutoUpdateEnabledPreference,
    readNotificationEnabledPreference,
    readLastNotifiedRemoteBuildNumber,
    writeLastNotifiedRemoteBuildNumber,
    buildNotificationTextPayload,
    getLatestDailyState,
    resolveUpdateCheckDecision,
    shouldResyncManualUpdatePolicy,
    showInAppToast,
    resolveNewVersionToastText,
    resolveNewVersionTitleText,
    resolveNewVersionBodyText,
    resolveUpdateApplyFailureToastText,
    setUpdateProgressOverlayActive,
    updateCheckThrottleMs,
    updateApplyReloadFallbackMs,
    dailyCheckTag,
    dailyNotificationWarningHours,
    waitingWorkerTimeoutFirstMs,
    waitingWorkerTimeoutRetryMs,
    fetchImpl,
    windowObj,
    documentObj,
    navigatorObj,
    notificationApi,
    now,
  });

  return {
    canUseServiceWorker: () => swMessenger.canUseServiceWorker(),
    supportsNotifications: () => swMessenger.supportsNotifications(),
    postMessageToServiceWorker: (message, postOptions = {}) => swMessenger.postMessage(message, postOptions),
    syncDailyStateToServiceWorker: () => swUpdateOrchestrator.syncDailyStateToServiceWorker(),
    syncUpdatePolicyToServiceWorker: () => swUpdateOrchestrator.syncUpdatePolicyToServiceWorker(),
    ensureServiceWorkerUpdatePolicyConsistency: () => swUpdateOrchestrator.ensureServiceWorkerUpdatePolicyConsistency(),
    requestServiceWorkerDailyCheck: () => swUpdateOrchestrator.requestServiceWorkerDailyCheck(),
    registerBackgroundDailyCheck: () => swUpdateOrchestrator.registerBackgroundDailyCheck(),
    clearAppliedUpdateHistoryActions: (appliedBuildNumber) => swUpdateOrchestrator.clearAppliedUpdateHistoryActions(appliedBuildNumber),
    fetchRemoteBuildNumber: () => swUpdateOrchestrator.fetchRemoteBuildNumber(),
    resolveUpdatableRemoteBuildNumber: (remoteBuildNumber) => swUpdateOrchestrator.resolveUpdatableRemoteBuildNumber(remoteBuildNumber),
    applyUpdateForBuild: (remoteBuildNumber, applyOptions = {}) => swUpdateOrchestrator.applyUpdateForBuild(remoteBuildNumber, applyOptions),
    checkForNewBuild: (checkOptions = {}) => swUpdateOrchestrator.checkForNewBuild(checkOptions),
    registerServiceWorker: () => swUpdateOrchestrator.registerServiceWorker(),
    bindServiceWorkerRuntimeEvents: () => swUpdateOrchestrator.bindRuntimeEvents(),
    bindServiceWorkerHistoryMessages: ({ onPayload }) => swUpdateOrchestrator.bindHistoryUpdates({ onPayload }),
    getRegistration: () => swUpdateOrchestrator.getRegistration(),
  };
}
