// Runtime loader for compact infinite override payload.
// Payload file is generated by scripts/build_infinite_overrides.js.
import { INFINITE_OVERRIDES_MODULE_FILE } from './shared/paths.ts';
import { decodePackedOverridePayload } from './shared/packed_override_codec.ts';

const FORMAT_MAGIC = 0x49; // 'I'
const FORMAT_VERSION = 1;
const IS_NODE = typeof process !== 'undefined' && Boolean(process?.versions?.node);
const GZIP_MAGIC_0 = 0x1f;
const GZIP_MAGIC_1 = 0x8b;
const NODE_FS_PROMISES_SPECIFIER = 'node:fs/promises';
const NODE_ZLIB_SPECIFIER = 'node:zlib';
const INFINITE_OVERRIDE_CODEC_MESSAGES = Object.freeze({
  invalidVarint: 'Invalid varint in infinite overrides payload',
  truncatedVarint: 'Truncated varint in infinite overrides payload',
  invalidHeader: 'Invalid infinite overrides payload header',
  unsupportedFormat: 'Unsupported infinite overrides payload format',
  invalidVariantBits: (variantBits: number) => `Invalid infinite overrides variant-bit width: ${variantBits}`,
  invalidDelta: 'Invalid infinite overrides delta encoding',
});

type DecodedOverrideMap = Readonly<Record<number, number>>;

interface NodeFsModule {
  readFile: (url: URL) => Promise<Uint8Array | ArrayBuffer>;
}

interface NodeZlibModule {
  gunzipSync: (input: Uint8Array) => Uint8Array | ArrayBuffer;
}

const decodePackedOverridePayloadTyped = decodePackedOverridePayload as (
  bytes: Uint8Array,
  options: {
    formatMagic: number;
    formatVersion: number;
    messages: Record<string, string | ((value: number) => string)>;
  },
) => DecodedOverrideMap;

const readCompressedOverrideBytes = async (): Promise<Uint8Array | null> => {
  const url = new URL(INFINITE_OVERRIDES_MODULE_FILE, import.meta.url);

  if (IS_NODE) {
    const { readFile } = await import(/* @vite-ignore */ NODE_FS_PROMISES_SPECIFIER) as NodeFsModule;
    try {
      return new Uint8Array(await readFile(url));
    } catch (error) {
      const code = error && typeof error === 'object' ? (error as { code?: string }).code : undefined;
      if (code === 'ENOENT') {
        // Allow builder scripts to run before the binary payload is emitted.
        return null;
      }
      throw error;
    }
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to load infinite overrides payload: ${response.status} ${response.statusText}`);
  }
  return new Uint8Array(await response.arrayBuffer());
};

const gunzipBytes = async (compressedBytes: Uint8Array | null): Promise<Uint8Array | null> => {
  if (!compressedBytes) return null;

  if (typeof DecompressionStream === 'function') {
    const browserBytes = Uint8Array.from(compressedBytes);
    const stream = new Blob([browserBytes]).stream().pipeThrough(new DecompressionStream('gzip'));
    return new Uint8Array(await new Response(stream).arrayBuffer());
  }

  if (IS_NODE) {
    const { gunzipSync } = await import(/* @vite-ignore */ NODE_ZLIB_SPECIFIER) as NodeZlibModule;
    return new Uint8Array(gunzipSync(compressedBytes));
  }

  throw new Error('DecompressionStream is unavailable; cannot decode infinite overrides payload');
};

const decodePackedOverrides = (bytes: Uint8Array): DecodedOverrideMap =>
  decodePackedOverridePayloadTyped(bytes, {
    formatMagic: FORMAT_MAGIC,
    formatVersion: FORMAT_VERSION,
    messages: INFINITE_OVERRIDE_CODEC_MESSAGES,
  });

const hasGzipHeader = (bytes: Uint8Array | null | undefined): boolean => {
  if (!bytes || bytes.length < 2) return false;
  return bytes[0] === GZIP_MAGIC_0 && bytes[1] === GZIP_MAGIC_1;
};

const decodeOverridePayloadBytes = async (bytes: Uint8Array | null): Promise<DecodedOverrideMap> => {
  const payloadBytes = hasGzipHeader(bytes) ? await gunzipBytes(bytes) : bytes;
  if (!payloadBytes) return Object.freeze(Object.create(null)) as DecodedOverrideMap;
  return decodePackedOverrides(payloadBytes);
};

const loadOverrideMap = async (): Promise<DecodedOverrideMap> => {
  const compressedBytes = await readCompressedOverrideBytes();
  return decodeOverridePayloadBytes(compressedBytes);
};

export const INFINITE_OVERRIDE_BY_INDEX = await loadOverrideMap().catch((err) => {
  console.error("Failed to load infinite overrides payload:", err);
  return Object.freeze(Object.create(null));
});

export const __TEST__ = {
  decodePackedOverrides,
  decodeOverridePayloadBytes,
  hasGzipHeader,
};
